
export const state = {
    user: [],
    repairAllColumn: [
        { 'id': 1, 'title': '№', 'value': 'title'},
        { 'id': 2, 'title': 'Клиент', 'value': 'client'},
        { 'id': 3, 'title': 'Обнаруженная неисправность', 'value': 'masterNotes'},
        { 'id': 4, 'title': 'Устройство', 'value': 'device'},
        { 'id': 5, 'title': 'Ожидаемая стоимость', 'value': 'plannedPrice'},
        { 'id': 6, 'title': 'Статус', 'value': 'status'},
        { 'id': 7, 'title': 'Заметки', 'value': 'acceptorNotes'},
        { 'id': 8, 'title': 'Дата выдачи', 'value': 'outDate'},
        { 'id': 9, 'title': 'Состояние', 'value': 'state'},
        { 'id': 10, 'title': 'Контактное лицо', 'value': 'clientContactName'},
        { 'id': 11, 'title': 'Email клиента', 'value': 'clientEmail'},
        { 'id': 12, 'title': 'Ожидаемая дата выдачи', 'value': 'plannedOutDate'},
        { 'id': 13, 'title': 'Тип устройства', 'value': 'deviceType'},
        { 'id': 14, 'title': 'Дата готовности', 'value': 'done_at'},
        { 'id': 15, 'title': 'Дата приема', 'value': 'incomeDate'},
        { 'id': 16, 'title': 'Адрес клиента', 'value': 'clientAddress'},
        { 'id': 17, 'title': 'К оплате', 'value': 'toPay'},
        { 'id': 18, 'title': 'Откуда узнал', 'value': 'clientSource'},
        { 'id': 19, 'title': 'Серийный номер/IMEI', 'value': 'serial'},
        { 'id': 20, 'title': 'Пункт приема', 'value': 'point'},
        { 'id': 21, 'title': 'Инженер', 'value': 'master'},
        { 'id': 22, 'title': 'Телефон клиента', 'value': 'phone'},
        { 'id': 23, 'title': 'Предоплата', 'value': 'prepayment'},
        { 'id': 24, 'title': 'Итого за ремонт', 'value': 'totalSum'},
        { 'id': 25, 'title': 'Приемщик', 'value': 'acceptor'},
        { 'id': 26, 'title': 'Неисправность', 'value': 'bug'},
        { 'id': 27, 'title': 'Гарантия до', 'value': 'warrant_until'},
        { 'id': 28, 'title': 'Срок гарантии', 'value': 'warrantSize'},
        { 'id': 29, 'title': 'Комплектация', 'value': 'equipment'},
        { 'id': 30, 'title': 'Выдал', 'value': 'ejector'},
    ],
    repairActiveColumn: [
        'title',
        'incomeDate',
        'client',
        'phone',
        'prepayment',
        'state',
        'device',
        'equipment',
        'status'
    ]
};